-- AlterTable
ALTER TABLE "User"
ADD COLUMN "globalUserId" TEXT NOT NULL DEFAULT '',
ADD COLUMN "fname" TEXT NOT NULL DEFAULT '',
ADD COLUMN "mname" TEXT NOT NULL DEFAULT '',
ADD COLUMN "lname" TEXT NOT NULL DEFAULT '',
ADD COLUMN "gender" TEXT NOT NULL DEFAULT '',
ADD COLUMN "dob" TEXT NOT NULL DEFAULT '',
ADD COLUMN "nationality" TEXT NOT NULL DEFAULT '',
ADD COLUMN "countryresidence" TEXT NOT NULL DEFAULT '',
ADD COLUMN "cityresidence" TEXT NOT NULL DEFAULT '',
ADD COLUMN "residentaladdress" TEXT NOT NULL DEFAULT '';

-- Drop old column
ALTER TABLE "User"
DROP COLUMN "name";

ALTER TABLE "User"
ADD COLUMN "mobile" TEXT NOT NULL DEFAULT '',
ADD COLUMN "countryCode" TEXT NOT NULL DEFAULT '';